### ISSUE TITLE
TypeError: argument 0 is not a Variable

### ISSUE THREAD

**Issue by redhat12345** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#3]
Got the following error.

Traceback (most recent call last):
  File "main_fine_tuning.py", line 260, in <module>
    num_epochs=100)
  File "main_fine_tuning.py", line 177, in train_model
    outputs = model(inputs)
  File "/home/user/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/pytorch_python2/local/lib/python2.7/site-packages/torchvision/models/resnet.py", line 139, in forward
    x = self.conv1(x)
  File "/home/user/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/userj/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/user/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
TypeError: argument 0 is not a Variable

**Comment by Otomadmt** [comment]
The input to conv layers should be a torch.autograd.Variable.
Try changing `outputs = model(inputs)` to:
```
from torch.autograd import Variable  
outputs = model(Variable(inputs))
```

**Comment by Paranoidv** [comment]
I have encounter this problem, but @Otomadmt I have test your solve idea, but it cat solve this problem

**Comment by Quasimondo** [comment]
The error that causes this actually happens a few line before that, but since it is caught in try/except it does not show. Change lines 167 to 171 from:

```
try:
    inputs, labels = Variable(inputs.float().cuda()),                             
    Variable(labels.long().cuda())
except:
    print(inputs,labels)
```


to:

```
try:
    inputs = Variable(inputs.float().cuda())                           
    labels = Variable(labels.long().cuda())
except:
    print(inputs,labels)
```

**Comment by Spandan-Madan** [comment]
Was this issue solved? If so I can go ahead and close it.

**Comment by Spandan-Madan** [comment]
As there's no responses on this, I'll assume this was solved and am closing the issue. Please reopen it if someone faces this!
