### ISSUE TITLE
AttributeError: 'ResNet' object has no attribute 'save_state_dict'

### ISSUE THREAD

**Issue by monajalal** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#9]
```
torch.Size([3, 3, 224, 224])
trying epoch loss
val Loss: 0.0533 Acc: 0.7712
Training complete in 96m 49s
Best val Acc: 0.790850
returning and looping back
Traceback (most recent call last):
  File "main_fine_tuning.py", line 267, in <module>
    model_ft.save_state_dict('fine_tuned_best_model.pt')
  File "/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'save_state_dict'
[jalal@goku Pytorch_fine_tuning_Tutorial]$ 

>>> import torch
>>> torch.__version__
'0.4.1.post2'

```

**Comment by MarcinMisiurewicz** [comment]
I think correct way to save state dict is:
`torch.save(model.state_dict(), PATH)`
as stated in https://pytorch.org/tutorials/beginner/saving_loading_models.html
